#!/bin/bash

set -e
set -u

# This pre-push hook runs various checks on the files that were modified
# on this branch.
#
# To push without running the pre-push hook, use `git push --no-verify`

GIT_ROOT=$(git rev-parse --show-toplevel)

if [ -n "$(git status --porcelain)" ]; then
    echo >&2 "pre-push: Error: The working tree has uncommitted changes."
    exit 1
fi

echo >&2 "pre-push: Running \`make fmt/check\`"
make -C "${GIT_ROOT}" --quiet fmt/check

echo >&2 "pre-push: Running \`tidy/check\` "
make -C "${GIT_ROOT}" --quiet tidy/check

echo >&2 "pre-push: Running \`make lint\`"
make -C "${GIT_ROOT}" --quiet lint 

# Check if the string "DO-NOT-PUSH" is present anywhere in this
# repository (except for this file itself)
if [ -n "$(git grep DO-NOT-PUSH -- ':(exclude)*/pre-push')" ]; then
    echo >&2 "pre-push: Error: Found string DO-NOT-PUSH"
    exit 1
fi
